const IMPULSES = [
  `Block Inside`,
  `Bottle Hall`,
  `Cement Blocks 1`,
  `Cement Blocks 2`,
  `Chateau de Logne, Outside`,
  `Conic Long Echo Hall`,
  `Deep Space`,
  `Derlon Sanctuary`,
  `Direct Cabinet N1`,
  `Direct Cabinet N2`,
  `Direct Cabinet N3`,
  `Direct Cabinet N4`,
  `Five Columns Long`,
  `Five Columns`,
  `French 18th Century Salon`,
  `Going Home`,
  `Greek 7 Echo Hall`,
  `Highly Damped Large Room`,
  `In The Silo Revised`,
  `In The Silo`,
  `Large Bottle Hall`,
  `Large Long Echo Hall`,
  `Large Wide Echo Hall`,
  `Masonic Lodge`,
  `Musikvereinsaal`,
  `Narrow Bumpy Space`,
  `Nice Drum Room`,
  `On a Star`,
  `Parking Garage`,
  `Rays`,
  `Right Glass Triangle`,
  `Ruby Room`,
  `Scala Milan Opera Hall`,
  `Small Drum Room`,
  `Small Prehistoric Cave`,
  `St Nicolaes Church`,
  `Trig Room`,
  `Vocal Duo`,
];

export { IMPULSES };
